### ISSUE TITLE
model.Bucket: new index attribute

### ISSUE THREAD

**Issue by steenzout** [Storj/storj-python-sdk#107]
```
Adds index to bucket entry model for the purpose of deprecating the deterministic bucket_id and file_id
```

- double check what this means
- change what needs to changed

**Comment by steenzout** [comment]
related [commit](https://github.com/Storj/storj-python-sdk/commit/23268e2e1ad722288185c04f04170d45c5cc1b39).

**Comment by lakewik** [comment]
Done
