### ISSUE TITLE
bucket_files name is misleading

### ISSUE THREAD

**Issue by frdwrd** [Storj/storj-python-sdk#21]
In http.py, I would expect `bucket_files()` to get a list of all files in a bucket. Instead it gets the pointers for a specific file. I can't find a function to list the files in a bucket.

Current functionality:
`bucket_files` gets file pointers via `GET /buckets/{id}/files/{file_id}`

Proposed change
`bucket_files` should list files in a bucket via `GET /buckets/{id}/files`
`file_pointers` should get file pointers via `GET /buckets/{id}/files/{file_id}`

**Comment by steenzout** [comment]
why not `bucket_file_pointers`? you're still working on a `bucket` domain.

**Comment by frdwrd** [comment]
All of the endpoints for file-related operations are actually variations on `/buckets/{id}/file/`. We already have `file_get`, `file_upload`, `file_delete`. `file_pointers` is consistent with these.

**Comment by steenzout** [comment]
got it.
