### ISSUE TITLE
ShardManager uses hardcoded path to C:/

### ISSUE THREAD

**Issue by frdwrd** [Storj/storj-python-sdk#37]
https://github.com/Storj/storj-python-sdk/blob/master/storj/model.py#L246

Replace with path to standard temp dir in the native file system.

**Comment by steenzout** [comment]
I thought you removed this piece of code?

if you still need it you can get something equivalent with:

```
            tmpdir = tempfile.mkdtemp()
            with open('%s/%s.shard' % (tmpdir, self.index)) as tmpfile:
                tmpfile.write(chunk)
```

**Comment by frdwrd** [comment]
This was fixed at some point. Closing the issue.
