### ISSUE TITLE
update the docs and README

### ISSUE THREAD

**Issue by steenzout** [Storj/storj-python-sdk#51]
The current README file is obsolete.
I propose to clean it up, simplify it and start creating the _real_ documentation on [readthedocs](http://storj-python-sdk.readthedocs.io/en/latest/).

please assign this to me.

**Comment by hrhristov** [comment]
I would like to point out that https://pypi.python.org/pypi/storj/ is also obsolete

**Comment by steenzout** [comment]
@hrhristov fixed: https://pypi.python.org/pypi .
