### ISSUE TITLE
Readme instructions are not working

### ISSUE THREAD

**Issue by hrhristov** [Storj/storj-python-sdk#72]
There are no such methods as storj.authenticate, storj.buckets.all, etc.

**Comment by steenzout** [comment]
_included on #51_

**Comment by hrhristov** [comment]
Sorry, from the #51 title it was not clear for me that the issue is the same. Maybe it should be "update", not "updated". I hope this will be fixed soon.

**Comment by steenzout** [comment]
#51 title fixed.

@hrhristov I'll make it my number 1 priority and see what I can do during this holiday season.

please subscribe to #51.

@Miskerest I suggest we close this one.

**Comment by steenzout** [comment]
#73 and #74 made to prevent users from trying to use obsolete instructions.
